'use strict';(function(){var cmpFile='noModule'in HTMLScriptElement.prototype?'cmp2.js':'cmp2-polyfilled.js';(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpUrl;var tagUrl=document.currentScript.src;cmpUrl='https://cmp.inmobi.com/tcfv2/53/CMP_FILE?referer=www.perfil.com'.replace('CMP_FILE',cmpFile);cmpScriptElement.src=cmpUrl;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button { "
+"   background-color: #5078A8 !important; "
+"   border-color: #5078A8 !important; "
+" } "
+" .qc-cmp-button:hover { "
+"   border-color: #5078A8 !important; "
+" } "
+" .qc-cmp-alt-action, "
+" .qc-cmp-link { "
+"   color: #5078A8 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #5078A8 !important; "
+"   border-color: #5078A8 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #ffffff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #368bd6 !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #eee !important; "
+"   border-color: transparent !important; "
+" } "
+""
+"";var stylesElement=document.createElement('style');var re=new RegExp('&quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();var autoDetectedLanguage='en';var gvlVersion=3;function splitLang(lang){if(lang.includes('pt')&&lang.length>2){return lang.split('-')[0]+'-'+lang.split('-')[1].toLowerCase();}
return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['en','fr','de','it','es','da','nl','el','hu','pt','pt-br','pt-pt','ro','fi','pl','sk','sv','no','ru','bg','ca','cs','et','hr','lt','lv','mt','sl','tr','uk','zh','id','ko','ja','hi','vi','th','ms'];return langs.indexOf(lang)===-1?false:true;};if(gvlVersion===2&&isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(gvlVersion===3&&isSupported(document.documentElement.lang)){autoDetectedLanguage=document.documentElement.lang;}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__tcfapi('init',2,function(){},{"coreConfig":{"siteUuid":"816ac47a-d52d-4017-b1bf-c2a5a4bfe9b2","themeUuid":"8699d889-6bdb-4ec5-99a4-1edff996babe","inmobiAccountId":"JLynYhbuKN0hh","privacyMode":["GDPR"],"includeVendorsDisclosedSegment":false,"cmpVersion":"53","hashCode":"QNC9XcqdRtKMrdn4zTlE8w","publisherCountryCode":"AR","publisherName":"Perfil","vendorPurposeIds":[1,2,7,8,10,11,3,5,4,9,6],"vendorFeaturesIds":[1,2,3],"vendorPurposeLegitimateInterestIds":[7,8,9,2,10,11],"vendorSpecialFeaturesIds":[2,1],"vendorSpecialPurposesIds":[1,2],"googleEnabled":true,"consentScope":"service","thirdPartyStorageType":"iframe","consentOnSafari":false,"displayUi":"inEU","defaultToggleValue":"off","initScreenRejectButtonShowing":true,"initScreenCloseButtonShowing":false,"softOptInEnabled":false,"showSummaryView":true,"persistentConsentLinkLocation":3,"displayPersistentConsentLink":true,"uiLayout":"banner","publisherLogo":"https://www.perfil.com/images/favicon/android-icon-192x192.png?qc-size=192,192","vendorListUpdateFreq":30,"publisherPurposeIds":[],"initScreenBodyTextOption":1,"publisherConsentRestrictionIds":[],"publisherLIRestrictionIds":[],"publisherPurposeLegitimateInterestIds":[],"publisherSpecialPurposesIds":[],"publisherFeaturesIds":[],"publisherSpecialFeaturesIds":[],"stacks":[1,42],"lang_":autoDetectedLanguage,"supportedLanguages":["bg","cs","da","de","el","en","es","et","fi","fr","hr","hu","it","lt","lv","mt","nl","no","pl","pt-br","pt-pt","ro","ru","sk","sl","sv","uk","tr","ja","id","ko","zh","hi","vi","th","ms"],"gvlVersion":3,"totalVendors":914,"gbcConfig":{"enabled":true,"urlPassThrough":null,"adsDataRedaction":null,"locations":["EEA"],"applicablePurposes":[{"id":1,"defaultValue":"GRANTED"},{"id":2,"defaultValue":"GRANTED"},{"id":3,"defaultValue":"GRANTED"},{"id":4,"defaultValue":"GRANTED"},{"id":5,"defaultValue":"GRANTED"},{"id":6,"defaultValue":"GRANTED"},{"id":7,"defaultValue":"GRANTED"}]},"legitimateInterestOptIn":true,"features":{"visitEvents":true},"translationUrls":{"common":"https://cmp.inmobi.com/tcfv2/translations/${language}.json","theme":"https://cmp.inmobi.com/custom-translations/JLynYhbuKN0hh/8699d889-6bdb-4ec5-99a4-1edff996babe/${language}.json","all":"https://cmp.inmobi.com/consolidated-translations/JLynYhbuKN0hh/8699d889-6bdb-4ec5-99a4-1edff996babe/${language}.json"},"gdprEnabledInUS":false},"premiumUiLabels":{},"premiumProperties":{"googleWhitelist":[1]},"coreUiLabels":{"initScreenRejectButton":"RECHAZAR","saveAndExitButton":"GUARDAR Y SALIR","agreeButton":"DE ACUERDO"},"theme":{"uxPrimaryButtonColor":"#5078A8"},"nonIabVendorsInfo":{}});})();